apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-pbjn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-pbjn
    app.kubernetes.io/part-of: tkrw-pr712-0075-0029-app
  name: devfile-sample-pbjn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-pbjn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-pbjn
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0029-tenant/tkrw-pr712-0075-0029-app/devfile-sample-pbjn@sha256:baea69ec7c18ed899c9dc02bf20b0cdfe357bdc06d8f8c0b2991b527d6adf6b9
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
